# Generated by Django 4.1.6 on 2023-04-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=3)),
                ('catalog_num', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('rate', models.FloatField(null=True)),
                ('bio', models.TextField(max_length=500, null=True)),
                ('available_times', models.JSONField(null=True)),
                ('profile_complete', models.BooleanField(null=True)),
                ('courses', models.ManyToManyField(null=True, to='tutor.course')),
            ],
        ),
    ]
