# Generated by Django 4.1.6 on 2023-04-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=3)),
                ('hour_of_day', models.CharField(choices=[('08:00', '8:00 AM'), ('09:00', '9:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '1:00 PM'), ('14:00', '2:00 PM'), ('15:00', '3:00 PM'), ('16:00', '4:00 PM'), ('17:00', '5:00 PM'), ('18:00', '6:00 PM'), ('19:00', '7:00 PM'), ('20:00', '8:00 PM'), ('21:00', '9:00 PM')], max_length=5)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='available_times_next_week',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='available_times',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='courses',
            field=models.ManyToManyField(to='tutor.course'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('subject', 'catalog_num', 'title')},
        ),
        migrations.AddField(
            model_name='tutor',
            name='availability',
            field=models.ManyToManyField(null=True, to='tutor.duration'),
        ),
    ]
