# Generated by Django 4.1.6 on 2023-04-26 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_availability_duration_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tutor.course'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.duration'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='past',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('testimonial', models.TextField(null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.appointment')),
            ],
        ),
    ]
